const germanFlag = 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg';
const spanishFlag = 'https://upload.wikimedia.org/wikipedia/commons/8/89/Bandera_de_Espa%C3%B1a.svg';
const frenchFlag = 'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg';
const italianFlag = 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg';

const data = {
    banners: [
        { id: 1,
        name: 'Banner1',
        src: 'https://images.unsplash.com/photo-1531256379416-9f000e90aacc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmFubmVyfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
        content: "aaaaaaaaaaaaaaaaaa",
    },
    { id: 2,
        name: 'Banner2',
        src: 'https://images.unsplash.com/photo-1500989145603-8e7ef71d639e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8YmxvZ3xlbnwwfHwwfHw%3D&w=1000&q=80',
        content: "bbbbbbbbbbbbbbbbbb",
    },
    { id: 3,
        name: 'Banner3',
        src: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwcm9maWxlLXBhZ2V8M3x8fGVufDB8fHx8&w=1000&q=80',
        content: "cccccccccccccccccc",
    },
    ],
    courses: [
        { id: 1,
        name: 'German 1',
        img: germanFlag,
        language: "German",
        users: 32123,
    },
    { id: 2,
        name: 'German 2',
        img: germanFlag,
        language: "German",
        users: 21302,
    },
    { id: 3,
        name: 'German 3',
        img: germanFlag,
        language: "German",
        users: 18860,
    },
    { id: 4,
        name: 'Spanish 1',
        img: spanishFlag,
        language: "Spanish",
        users: 60135,
    },
    { id: 5,
        name: 'Spanish 2',
        img: spanishFlag,
        language: "Spanish",
        users: 30229,
    },
    { id: 6,
        name: 'Spanish 3',
        img: spanishFlag,
        language: "Spanish",
        users: 21033,
    },
    { id: 7,
        name: 'French 1',
        img: frenchFlag,
        language: "French",
        users: 34033,
    },
    { id: 8,
        name: 'French 2',
        img: frenchFlag,
        language: "French",
        users: 25352,
    },
    { id: 9,
        name: 'French 3',
        img: frenchFlag,
        language: "French",
        users: 20034,
    },
    { id: 10,
        name: 'Italian 1',
        img: italianFlag,
        language: "Italian",
        users: 42186,
    },
    { id: 11,
        name: 'Italian 2',
        img: italianFlag,
        language: "Italian",
        users: 16469,
    },
    { id: 12,
        name: 'Italian 3',
        img: italianFlag,
        language: "Italian",
        users: 12444,
    },
    { id: 13,
        name: 'French 4',
        img: frenchFlag,
        language: "French",
        users: 9034,
    },
    { id: 14,
        name: 'Spanish 4',
        img: spanishFlag,
        language: "Spanish",
        users: 17008,
    },
    ]
}

export default data;