const germanFlag = 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg';
const spanishFlag = 'https://upload.wikimedia.org/wikipedia/commons/8/89/Bandera_de_Espa%C3%B1a.svg';
const frenchFlag = 'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg';
const italianFlag = 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg';

const data = {
    banners: [
        { id: 1,
        name: 'Banner1',
        src: 'https://www.simplyrecipes.com/thmb/8caxM88NgxZjz-T2aeRW3xjhzBg=/2000x1125/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__09__easy-pepperoni-pizza-lead-3-8f256746d649404baa36a44d271329bc.jpg',
        content: "aaaaaaaaaaaaaaaaaa",
    },
    { id: 2,
        name: 'Banner2',
        src: 'https://m.media-amazon.com/images/I/61Q7SR0r9XL._SL1500_.jpg',
        content: "bbbbbbbbbbbbbbbbbb",
    },
    { id: 3,
        name: 'Banner3',
        src: 'https://image.shutterstock.com/image-photo/single-potato-french-fry-chip-260nw-567056539.jpg',
        content: "cccccccccccccccccc",
    },
    ],
    courses: [
        { id: 1,
        name: 'German 1',
        img: germanFlag,
        language: "German",
        users: 40123,
    },
    { id: 2,
        name: 'German 2',
        img: germanFlag,
        language: "German",
        users: 21302,
    },
    { id: 3,
        name: 'German 3',
        img: germanFlag,
        language: "German",
        users: 18860,
    },
    { id: 4,
        name: 'Spanish 1',
        img: spanishFlag,
        language: "Spanish",
        users: 60135,
    },
    { id: 5,
        name: 'Spanish 2',
        img: spanishFlag,
        language: "Spanish",
        users: 30229,
    },
    { id: 6,
        name: 'Spanish 3',
        img: spanishFlag,
        language: "Spanish",
        users: 21033,
    },
    { id: 7,
        name: 'French 1',
        img: frenchFlag,
        language: "French",
        users: 29033,
    },
    { id: 8,
        name: 'French 2',
        img: frenchFlag,
        language: "French",
        users: 25352,
    },
    { id: 9,
        name: 'French 3',
        img: frenchFlag,
        language: "French",
        users: 20034,
    },
    { id: 10,
        name: 'Italian 1',
        img: italianFlag,
        language: "Italian",
        users: 25186,
    },
    { id: 11,
        name: 'Italian 2',
        img: italianFlag,
        language: "Italian",
        users: 16469,
    },
    { id: 12,
        name: 'Italian 3',
        img: italianFlag,
        language: "Italian",
        users: 12444,
    },
    { id: 13,
        name: 'French 4',
        img: frenchFlag,
        language: "French",
        users: 9034,
    },
    ]
}

export default data;
